"""Add channel_id to Article

Revision ID: d1883b92fee5
Revises: 
Create Date: 2025-03-11 12:52:50.492172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import Integer, String

# revision identifiers, used by Alembic.
revision = 'd1883b92fee5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():

    try:
        with op.batch_alter_table('article', schema=None) as batch_op:
            batch_op.add_column(sa.Column('channel_id', sa.Integer(), nullable=True))
    except sa.exc.OperationalError:
        pass

    # All existing articles were from FAZ channel
    conn = op.get_bind()

    channel_table = table('channel',
        column('id', Integer),
        column('title', String),
        column('link', String),
        column('description', String)
    )

    conn.execute(channel_table.insert().values(
        id = 1,
        title = 'Aktuell - FAZ.NET',
        link = 'https://www.faz.net/rss/aktuell/',
        description = 'News, Nachrichten und aktuelle Meldungen aus allen Ressorts. Politik, Wirtschaft, Sport, Feuilleton und Finanzen im Überblick.')
        )


    article_table = table('article', column('channel_id', Integer))
    conn.execute(article_table.update().values(channel_id=1))


    with op.batch_alter_table('article', schema=None) as batch_op:
        # Set `channel_id` auf NOT NULL setzen
        batch_op.alter_column('channel_id', nullable=False)
        # Add Foreign Key
        batch_op.create_foreign_key('fk_channel_id', 'channel', ['channel_id'], ['id'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint('fk_channel_id', type_='foreignkey')
        batch_op.drop_column('channel_id')

    # ### end Alembic commands ###
