"""Add cascade to channel-article relationship

Revision ID: f917a67c9681
Revises: d1883b92fee5
Create Date: 2025-04-22 10:12:31.911265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f917a67c9681'
down_revision = 'd1883b92fee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint('fk_channel_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_articles_id', 'channel', ['channel_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint('fk_articles_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_channel_id', 'channel', ['channel_id'], ['id'])

    # ### end Alembic commands ###
